### ISSUE TITLE
Task: Update link variables

### ISSUE THREAD

**Issue by shraacha** [wloocc/wloocc-website#4]
Make insta link a global variable so we don't have to change it everywhere.

**Comment by smchase** [comment]
Yeah, in the about for ex we should use the global Discord and Instagram variables instead of hard linking

**Comment by shraacha** [comment]
We can now do 

`[Instagram]({{% instagram_link %}})`

and same with discord.

This is done via shortcodes in the hugo theme (see themes/paper/layouts/shortcodes).
