### ISSUE TITLE
Favicon not showing in search

### ISSUE THREAD

**Issue by shraacha** [wloocc/wloocc-website#9]
![image](https://github.com/user-attachments/assets/50e2aebc-a23b-438f-b841-99f65a7d07d6)

**Comment by shraacha** [comment]
Added ico in commit 93eb9c2690, hopefully this works? Might have to wait until Google updates the icon.

**Comment by smchase** [comment]
Requested reindexing by Google

**Comment by smchase** [comment]
https://search.google.com/u/2/search-console/inspect?resource_id=https%3A%2F%2Fclimbing.uwaterloo.ca%2F&id=Y4T_p4ty9GEygp7RySc5GQ

**Comment by smchase** [comment]
<img width="552" alt="Screenshot 2024-08-06 at 6 16 09 PM" src="https://github.com/user-attachments/assets/66b9ce6e-731e-4bfd-868c-0ecb0066176e">

fixed
